// Auto-generated by GlassUiRegistry
import AppFolder from './AppFolder.vue'
import Container from './Container.vue'
import ContentPanel from './ContentPanel.vue'
import FlipCard from './FlipCard.vue'
import FlipClock from './FlipClock.vue'
import GlassActivityIndicator from './GlassActivityIndicator.vue'
import GlassAlert from './GlassAlert.vue'
import GlassAnalogClock from './GlassAnalogClock.vue'
import GlassBadge from './GlassBadge.vue'
import GlassButton from './GlassButton.vue'
import GlassCalendar from './GlassCalendar.vue'
import GlassCard from './GlassCard.vue'
import GlassCheckbox from './GlassCheckbox.vue'
import GlassCollectionContainer from './GlassCollectionContainer.vue'
import GlassContextMenu from './GlassContextMenu.vue'
import GlassDatePicker from './GlassDatePicker.vue'
import GlassDigitalClock from './GlassDigitalClock.vue'
import GlassDropdown from './GlassDropdown.vue'
import GlassHStack from './GlassHStack.vue'
import GlassIconButton from './GlassIconButton.vue'
import GlassImageButton from './GlassImageButton.vue'
import GlassInput from './GlassInput.vue'
import GlassListItem from './GlassListItem.vue'
import GlassModal from './GlassModal.vue'
import GlassNavBar from './GlassNavBar.vue'
import GlassPanel from './GlassPanel.vue'
import GlassProgressBar from './GlassProgressBar.vue'
import GlassProgressRing from './GlassProgressRing.vue'
import GlassScrollContainer from './GlassScrollContainer.vue'
import GlassSearchableDropdown from './GlassSearchableDropdown.vue'
import GlassSegmentedControl from './GlassSegmentedControl.vue'
import GlassSlider from './GlassSlider.vue'
import GlassSplitContainer from './GlassSplitContainer.vue'
import GlassStepper from './GlassStepper.vue'
import GlassTabBar from './GlassTabBar.vue'
import GlassTableContainer from './GlassTableContainer.vue'
import GlassTableRow from './GlassTableRow.vue'
import GlassTextarea from './GlassTextarea.vue'
import GlassThemeChooser from './GlassThemeChooser.vue'
import GlassToast from './GlassToast.vue'
import GlassToggle from './GlassToggle.vue'
import GlassVStack from './GlassVStack.vue'
import GlassValidatedInput from './GlassValidatedInput.vue'
import ImageButton from './ImageButton.vue'
import MenuBar from './MenuBar.vue'
import PasswordInput from './PasswordInput.vue'
import '../styles/styles.scss'
import { createPinia } from 'pinia'
import { ClickOutside } from '../directives/clickOutside'
import { BackgroundImage } from '../directives/imageBackground'
import { BackgroundMesh } from '../directives/meshBackground'

import { useThemeStore } from '../stores/themeStore'

export const GlassComponents = {
  AppFolder,
  Container,
  ContentPanel,
  FlipCard,
  FlipClock,
  GlassActivityIndicator,
  GlassAlert,
  GlassAnalogClock,
  GlassBadge,
  GlassButton,
  GlassCalendar,
  GlassCard,
  GlassCheckbox,
  GlassCollectionContainer,
  GlassContextMenu,
  GlassDatePicker,
  GlassDigitalClock,
  GlassDropdown,
  GlassHStack,
  GlassIconButton,
  GlassImageButton,
  GlassInput,
  GlassListItem,
  GlassModal,
  GlassNavBar,
  GlassPanel,
  GlassProgressBar,
  GlassProgressRing,
  GlassScrollContainer,
  GlassSearchableDropdown,
  GlassSegmentedControl,
  GlassSlider,
  GlassSplitContainer,
  GlassStepper,
  GlassTabBar,
  GlassTableContainer,
  GlassTableRow,
  GlassTextarea,
  GlassThemeChooser,
  GlassToast,
  GlassToggle,
  GlassVStack,
  GlassValidatedInput,
  ImageButton,
  MenuBar,
  PasswordInput,
};


export function  UseGlassUi(app) {
    const pinia = createPinia()
    app.directive('click-outside', ClickOutside);
    app.directive('background-image', BackgroundImage);
    app.directive('background-mesh', BackgroundMesh);
    app.use(pinia);
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
    const themeStore = useThemeStore()
    themeStore.restoreTheme()
};
