// Auto-generated by GlassUiRegistry
import FlipCard from './FlipCard.vue'
import IconView from './IconView.vue'
import UIActivityIndicator from './UIActivityIndicator.vue'
import UIAlert from './UIAlert.vue'
import UIAnalogClock from './UIAnalogClock.vue'
import UIButton from './UIButton.vue'
import UICollectionView from './UICollectionView.vue'
import UIDatePicker from './UIDatePicker.vue'
import UIDropdownList from './UIDropdownList.vue'
import UIFlipClock from './UIFlipClock.vue'
import UIImage from './UIImage.vue'
import UIImageView from './UIImageView.vue'
import UIListPicker from './UIListPicker.vue'
import UIModalDialog from './UIModalDialog.vue'
import UINavigationBar from './UINavigationBar.vue'
import UINotificationBar from './UINotificationBar.vue'
import UIPageControl from './UIPageControl.vue'
import UIPopover from './UIPopover.vue'
import UIProgressView from './UIProgressView.vue'
import UISearchBar from './UISearchBar.vue'
import UISlider from './UISlider.vue'
import UISplitView from './UISplitView.vue'
import UISwitch from './UISwitch.vue'
import UITabBar from './UITabBar.vue'
import UITabItem from './UITabItem.vue'
import UITableCell from './UITableCell.vue'
import UITableView from './UITableView.vue'
import UITextField from './UITextField.vue'
import UITextView from './UITextView.vue'
import UIThemeChooser from './UIThemeChooser.vue'
import UITimePicker from './UITimePicker.vue'
import UIToolbar from './UIToolbar.vue'
import UIVisualEffectView from './UIVisualEffectView.vue'
import UIWheelListView from './UIWheelListView.vue'
import UIWidgetView from './UIWidgetView.vue'
import '../styles/styles.scss'
import { createPinia } from 'pinia'
import { VisualEffect } from '@/directives/visualEffect'
import { BackgroundMesh } from '@/directives/backgroundMesh'
import { ClickOutside } from '@/directives/clickOutside'
import { useThemeStore } from '@/stores/themeStore'

export const GlassComponents = {
  FlipCard,
  IconView,
  UIActivityIndicator,
  UIAlert,
  UIAnalogClock,
  UIButton,
  UICollectionView,
  UIDatePicker,
  UIDropdownList,
  UIFlipClock,
  UIImage,
  UIImageView,
  UIListPicker,
  UIModalDialog,
  UINavigationBar,
  UINotificationBar,
  UIPageControl,
  UIPopover,
  UIProgressView,
  UISearchBar,
  UISlider,
  UISplitView,
  UISwitch,
  UITabBar,
  UITabItem,
  UITableCell,
  UITableView,
  UITextField,
  UITextView,
  UIThemeChooser,
  UITimePicker,
  UIToolbar,
  UIVisualEffectView,
  UIWheelListView,
  UIWidgetView,
};


export function  UseGlassUi(app) {
    const pinia = createPinia()
    app.directive('click-outside', ClickOutside);
    app.directive('visual-effect', VisualEffect);
    app.directive('background-mesh', BackgroundMesh);

    app.use(pinia);
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
    const themeStore = useThemeStore()
    themeStore.restoreTheme()
};
