import fs from 'fs'
import path from 'path'
import { normalizePath } from 'vite'

/**
 * Vite Plugin that performs two tasks:
 * 1. Generates a Virtual Module (in-memory) for immediate use via 'import ... from virtual:...'
 * 2. Generates a Static File (on-disk) for inspection and visibility.
 *
 * @param {Object} options
 * @param {string} options.directory - The source directory to scan for components (e.g., 'src/components/base').
 * @param {string} options.virtualModuleId - The ID used to import the generated code (e.g., 'virtual:registry').
 * @param {string} options.outputFile - The path for the generated plugin file (e.g., 'src/plugins/registry.js').
 */
export function GlassUiRegistry(options = {}) {
  const sourceDirectory = options.directory || 'src/components/base'
  const outputFile = options.outputFile || 'src/plugins/componentRegistry.js'
  const virtualModuleId = options.virtualModuleId || 'virtual:dynamic-registry'
  const resolvedVirtualModuleId = '\0' + virtualModuleId
  const renderScssSpa = options.scssSpa ? true : false

  // Absolute paths for file system operations
  const absoluteOutputDir = path.resolve(process.cwd(), path.dirname(outputFile))
  const absoluteOutputPath = path.resolve(process.cwd(), outputFile)
  const absoluteOutputScss = path.resolve(process.cwd(), 'src/styles/styles-full.scss')
  const absoluteOutputSpa = path.resolve(process.cwd(), 'src/styles/combined-spa.txt')

  const generateStaticSpa = () => {
    const stylesDirectory = 'src/styles/components'
    const files = fs.readdirSync(stylesDirectory)
    const scssFiles = files.filter((f) => f.endsWith('.scss'))

    const getFile = (file) => {
      const data = fs.readFileSync('./src/styles/' + file, 'utf-8')
      return `/* File: ${file} */\n${data}`
    }
    const scssImports = scssFiles.map((file) => {
      return getFile('./components/' + file)
    })

    return `${getFile('./themes/apple.scss')}
${getFile('./_typography.scss')}
${scssImports.join('\n')}`
  }

  const generateStaticScss = () => {
    const stylesDirectory = 'src/styles/components'
    const files = fs.readdirSync(stylesDirectory)
    const scssFiles = files.filter((f) => f.endsWith('.scss'))

    const scssImports = scssFiles.map((file) => {
      const name = file.replace('.scss', '')
      return `@use './components/${name}' as *;`
    })

    return `@use './themes/apple.scss' as *;
@use './_typography' as *;
${scssImports.join('\n')}`
  }

  const generateStaticCode = () => {
    const files = fs.readdirSync(sourceDirectory)
    const vueFiles = files.filter((f) => f.endsWith('.vue'))

    const registryEntries = vueFiles.map((file) => {
      const name = file.replace('.vue', '')
      return `import ${name} from './${file}'`
    })

    const exportFromEntries = vueFiles.map((file) => {
      const name = file.replace('.vue', '')
      return `export ${name} from './components/{file}'`
    })

    const exportEntries = vueFiles.map((file) => {
      const name = file.replace('.vue', '')
      return `  ${name},`
    })

    return `// Auto-generated by GlassUiRegistry
${registryEntries.join('\n')}
import '../styles/styles.scss'
import { createPinia } from 'pinia'
import { ClickOutside } from '../directives/clickOutside'
import { BackgroundImage } from '../directives/imageBackground'
import { BackgroundMesh } from '../directives/meshBackground'
import { BackgroundColor } from '../directives/colorBackground'
import { useThemeStore } from '../stores/themeStore'

export const GlassComponents = {
${exportEntries.join('\n')}
};


export function  UseGlassUi(app) {
    const pinia = createPinia()
    app.directive('click-outside', ClickOutside);
    app.directive('background-image', BackgroundImage);
    app.directive('background-mesh', BackgroundMesh);
    app.directive('background-color', BackgroundColor);

    app.use(pinia);
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
    const themeStore = useThemeStore()
    themeStore.restoreTheme()
};
`
  }

  /**
   * Helper function to generate the common plugin code block.
   * This code is used for both the virtual module and the static file.
   */
  const generatePluginCode = () => {
    // The glob pattern relative to the project root
    const globPattern = normalizePath('/' + sourceDirectory + '/*.vue')

    return `
            // This code block is dynamically generated by vite-plugin-combined-registry.js.
            // It is available both as a virtual module and a static file.

            export const GlassUiRegistry = {
                install(app) {
                    console.log("%c[VITE PLUGIN] Dynamic Registry Installation Start", "color: #8B5CF6; font-weight: bold;");

                    // 1. Component Registration (Dynamic using import.meta.glob)
                    const componentModules = import.meta.glob('${globPattern}', { eager: true });

                    for (const path in componentModules) {
                        const component = componentModules[path].default;

                        // Extract component name from path (e.g., /src/components/base/BaseButton.vue -> BaseButton)
                        const match = path.match(/\\/([^/]+)\\.vue$/i);
                        if (match) {
                            const name = match[1];
                            app.component(name, component);
                        }
                    }
                    console.log(\`[VITE PLUGIN] Registered \${Object.keys(componentModules).length} components globally.\`);

                    // 2. Add Global Controls/Utilities

                    /**
                     * Custom global control for logging application events.
                     * Available on component instances as this.$logControl()
                     */
                    app.config.globalProperties.$logControl = (type, message) => {
                        const timestamp = new Date().toLocaleTimeString();
                        console.info(\`%c[CONTROL:\${type}] \${message}\`, 'color: #EF4444; font-weight: bold;');
                    };

                    app.config.globalProperties.$appConfig = {
                        version: '4.0.0-combined',
                        registrySource: 'Combined Virtual & Static Generation'
                    };

                    console.log("%c[VITE PLUGIN] Dynamic Registry Complete", "color: #8B5CF6; font-weight: bold;");
                }
            };
        `
  }

  return {
    name: 'vite-plugin-combined-registry',
    enforce: 'pre',

    // --- A. STATIC FILE GENERATION (Triggered on build start) ---
    buildStart() {
      // Ensure the output directory exists
      if (!fs.existsSync(absoluteOutputDir)) {
        fs.mkdirSync(absoluteOutputDir, { recursive: true })
      }

      const spa = generateStaticSpa()
      const scss = generateStaticScss()
      const codeStatic = generateStaticCode()
      const code = generatePluginCode()

      // Write the generated code to the specified file path
      try {
        if (renderScssSpa) {fs.writeFileSync(absoluteOutputSpa, spa, 'utf-8')}
        fs.writeFileSync(absoluteOutputScss, scss, 'utf-8')
        fs.writeFileSync(absoluteOutputPath, codeStatic, 'utf-8')
        console.log(`[Vite Plugin] Wrote static registry file to: ${outputFile}`)
      } catch (error) {
        console.error(`[Vite Plugin] Failed to write component registry file: ${error}`)
      }
    },

    // --- B. VIRTUAL MODULE RESOLUTION (Handles imports) ---
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
      return null
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        // Return the generated code in memory for the virtual module import
        return generatePluginCode()
      }
      return null
    },
  }
}
